### ISSUE TITLE
Pre 2.0.0 heads dissapear when broken, but only if placed on the floor

### ISSUE THREAD

**Issue by Roan-V** [Zazsona/DecorHeads#7]
So here I am again ^_^
Weird bug, haven't had the time to test this but I've seen it happening on my server.

It seems that when a player breaks a placed pre 2.0.0 head they don't drop an item, but only if placed on the floor!
Placing them on the wall and then breaking works fine.

(I'm assuming it's pre 2.0.0 heads, they have different NBT data than the current ones, I'll verify this later at some point. Unless you fix it beforehand :P)

**Comment by Zazsona** [comment]
Might have to give you a regular's discount, haha. Cheers for another report!
You're right in it being pre-2.0.0 heads only! This one stems from a bug in pre-2.0.0 versions, where metadata was not retained between server reboots. Because of that, 2.0.0+ versions can't tell which head it originally was.

I've had a peek about and the reason the heads don't at least revert to the default head drop like before is because the plugin is globally preventing drops of *all* heads from *all* plugins apart from DecorHeads 2.0.0+! Can't imagine I'll be too popular with other head plugins with that there, or cases like this with the old heads.

 I'll be sure to get it patched to at least get those default head drops and not interfere with other plugins' heads! Cheers again!

**Comment by Zazsona** [comment]
Fixed to the point of not blocking drops from other plugins and restoring default Minecraft head drops (i.e X's Head) for broken legacy DecorHeads heads! (https://github.com/Zazsona/DecorHeads/commit/d1bce5b07819baf6fb28b5a4cb508a8a4ab656be)
Incidentally, it seems the reason old heads still dropped from walls is because DecorHeads isn't properly checking for heads in those positions so didn't block the drops... But apparently it also means new heads _don't_ drop from walls (Issue #8)! Talk about a jumble!

Might just be the cause of an issue I've been trying to debug with another user, too! So cheers again for leading me down that path, haha.
